### ISSUE TITLE
No que se difere este bot do oficial?

### ISSUE THREAD

**Issue by k4m4h4l** [EduardoRenz/Biscoint-Bitcoin-Arbitrage#1]
No que esta versao do bot se diifere da oficial fornecida pela biscoint?

**Comment by EduardoRenz** [comment]
Bom dia @k4m4h4l
Basicamente ser feito em Python.
A versão que a Biscoint disponibiliza de exemplo no site deles é em Node.

Mas note que usei a biblioteca oficial deles para as chamadas na API
```python
from biscoint_api_python import Biscoint
```

Encontrada em https://github.com/Biscoint/biscoint-api-python

**Comment by k4m4h4l** [comment]
Então amigo a minha dúvida era saber se a sua versão ajuda diminuir a quantidade de entradas no vermelho

**Comment by EduardoRenz** [comment]
Eu não testei a API Oficial ou em Node.
Mas alguns tem alguns pontos que talvez ajude.
- Se o Primeiro trade não ocorrer, o segundo não corre.
- Se o  primeiro trade ocorrer e o segundo não, não haverá um trade para recuperar o primeiro (assim não da vermelho, mas praticamente vai ter investido na moeda)
- Quando spread da arbitragem se aproxima de um valor baixo, a velocidade de verificação das ofertas aumenta, o que pode ajudar a ser um dos primeiros a pegar o trade.

Não está habilitado, mas tem uma versão de teste onde executa os 2 trades em paralelo, o que talvez reduza a quantidade de trades que falham, devido a demora da execução de um após o outro. No arquivo biscoint_official_api.ipynb tem esse teste com paralelismo, caso queira testar.

No fim acho que não tem como evitar os trades que falham, e talvez as informações e testes citados acima não façam mudanças significativas.  Mas o código está disponível para quem queira testar e modificar, a fim de tentar melhora-lo.
